FROM node:22-slim AS builder
ENV NODE_OPTIONS=--max-old-space-size=8192
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN corepack enable
WORKDIR /app
COPY frontend/ .
RUN pnpm install --frozen-lockfile
RUN pnpm run build:antd

FROM nginx:stable-alpine
COPY --from=builder /app/apps/web-antd/dist /usr/share/nginx/html
COPY deploy/nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
